### ISSUE TITLE
question about the size of the index file

### ISSUE THREAD

**Issue by tothuhien** [SilvioWeging/kASA#10]
Hi,
I have created 2 database indexes and each one have the size of ~2T. But when I merged them together using 'kASA merge' it was trying to create an index of 22T, and running for very long time without finishing. 
Do you have any idea if it's a bug or it's normal to have such big database size?
Thanks a lot.

**Comment by ghost** [comment]
Greetings,
that most certainly sounds like something went wrong. But in order to see where the error lies, I'll need more information. Could you please open the _info.txt files of the indices and post the content? Also: The full call to kASA and the output in the console would be helpful as well.
Thx

**Comment by tothuhien** [comment]
Hi, thanks for your response. I've checked the info file and actually it has wrong information. For some reason the info file was missing from the previous run so I created it by myself. Just fixed it and it seems to be normal now.
