### ISSUE TITLE
Installation-Building from source error

### ISSUE THREAD

**Issue by BhawnaY16** [SilvioWeging/kASA#11]
Hi
I've tried installing kasa using conda but the kasa build command gives me error- illegal instructions (core dumped).When I tried compiling the files using source,I am facing an error-
**[ 97%] Building CXX object CMakeFiles/kASA.dir/zlib/gzstream.cpp.o
make[2]: *** No rule to make target '../zlib/zlibBuild/libz.a', needed by 'kASA'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/kASA.dir/all] Error 2
make: *** [Makefile:152: all] Error 2**

I'm working in linux environment with config x86_64.
If you can kindly help me with the issue.Thank you!

**Comment by ghost** [comment]
Hi,
I have no idea why the build command from the conda installation fails because the information provided is not sufficient.
As for the built from source: Could it be, that you forgot to build the zlib beforehand? I tried the instructions from the Readme again on my Ubuntu 22.04 WSL and it worked so please double check if you've done it exactly as written.

**Comment by ghost** [comment]
Closed due to inactivity.
