### ISSUE TITLE
how to give input for paired end fastq read file

### ISSUE THREAD

**Issue by Ankita-1211** [SilvioWeging/kASA#2]
Please let me know how can i put paired end fastq as input.

**Comment by ghost** [comment]
Hi,
currently, kASA does not make use of paired-end information. Either you provide only one file or (if you want to check if results for both files are equal afterwards) put both them in a folder and provide the path ( -i `<path>/` ).

**Comment by Ankita-1211** [comment]
thank you for reply.

what would be your suggestion , if i merge the two paired end file into single fastq, will that be fine.
these day a lot of paired end sequences are generated why dint you put paired end as input?

**Comment by ghost** [comment]
I would suggest you only use one of the two files. The profiles of both files would be similar anyway and the per-read report is likely similar as well (depending on the amount of additional DNA the mate-pair contributes).

As to your second question:
Mainly due to other priorities. A working software can be expanded with features, a software with many features that aren't working is just bloatware. I chose to concentrate on the (in my opinion) more important stuff and add it to my TODO list instead (please see the end of the README). I'm sorry that I didn't point the lack of certain things out more clearly and for causing your confusion. But I hope this (admittedly pragmatic) answer is helping you understand my intentions.
