### ISSUE TITLE
kmer increase limit

### ISSUE THREAD

**Issue by Ankita-1211** [SilvioWeging/kASA#3]
Is there any way i can increase the upper limit for kmer from 12 to 17?
i have a specific requirement wherein i want a kmer length of 17.

**Comment by ghost** [comment]
Greetings,
unfortunately this is not possible. But just to be clear so that no misunderstandings occur: k=12 is meant on the amino acid-like level. This means that 36 bases are converted into 12 aa-letters and they are saved into a 64 bit integer (12*5 bits = 60 bits). Expanding this is not straightforward because C++ does not natively support 128 bit integers on all compilers yet. Furthermore, simply using two 64 bit integers is not a good solution since this has a huge impact on performance (I've tested this for myself a while ago). Until I've figured a way around this, we're stuck with 12 :/
Sorry to disappoint you again.
Sincerely,
Silvio

**Comment by Ankita-1211** [comment]
Thank you Silvio,

Since you have done a lot in this research, could you help me with metagenomic read aligner which can give me good accuracy , does a similar kind of work like your tool.

I am thinking of using diamond, as I need  reads converted to amino acid before aligning, but diamond takes lot of time.

**Comment by ghost** [comment]
Sure, no problem.

Oh well, read aligning is not really my field of expertise I must admit. I'm rather more interested in the algorithms themselves than using them for data analysis. Furthermore, kASA answers the question "Which known organisms are there?" in contrast to an aligner which is more like "Which loci does it come from exactly?". Advantage of kASA: more genomes, disadvantage: no exact locations in the genome which is exactly what an aligner provides (but unfortunately only for a couple of genomes lest runtimes explode).

So I can really only refer you to this more or less comprehensive list of tools for sequence alignment: https://en.wikipedia.org/wiki/List_of_sequence_alignment_software

If you have further questions to non-kASA related stuff, feel free to send an email. The issue page is more for actual bugs or missing features...
