### ISSUE TITLE
error: call of overloaded ‘isinf(double&)’ / ‘isnan(double&)’ is ambiguous (GCC 5.x)

### ISSUE THREAD

**Issue by ernstki** [SilvioWeging/kASA#4]
Hi Silvio,

I've attemped to build kASA with GCC 5.4.0, and I receive these two compiler errors (after having done `cmake ..` followed by `make` in the `build` directory, as per your instructions):

```
In file included from /path/to/kASA/source/modes/Compare.hpp:16:0,
                 from /path/to/kASA/source/main.cpp:13:
/path/to/kASA/source/modes/../utils/dToStr.h: In function ‘void dtoa_milo(double, std::__cxx11::string&)’:
/path/to/kASA/source/modes/../utils/dToStr.h:431:17: error: call of overloaded ‘isnan(double&)’ is ambiguous
  if (isnan(value)) {

[… other warnings redacted …]

In file included from /path/to/kASA/source/modes/Compare.hpp:16:0,
                 from /path/to/kASA/source/main.cpp:13:
/path/to/kASA/source/modes/../utils/dToStr.h:435:17: error: call of overloaded ‘isinf(double&)’ is ambiguous
  if (isinf(value)) {
                 ^
```

If you're wondering, I chose GCC 5.4.0 from among the [modules](http://modules.sourceforge.net/) on our cluster just because it had the required C++17 support, and was in the middle of the range of versions we had available, and that seemed "safe."

I should also note that kASA compiles without errors (two warnings about `control reaches end of non-void function`) with GCC 8.2.0. As this is a much more recent GCC version, I suppose the solution to the problem stated in this issue may well be "use a more recent version of GCC."

However, I wanted to record the error message here, for posterity, in case anyone else is stuck in an environment using an older GCC. Feel free to tag the issue "wontfix" and close it, as you see fit.

**Comment by ghost** [comment]
Hey Kevin,

thank you for bringing this to my attention! I really should be more sensitive to my namespaces :D 
Anyway, it's fixed now and I've tested it on 5.4.0-1 which is available on our cluster as well - without an issue now.

The warnings of `control reaches end of non-void function` come from the STXXL and are of no importance to kASA. Beyond that: C++17 is a nice-to-have but not really a requirement for it (just to be petty^^).

Closed because fixed.
