### ISSUE TITLE
ERROR: content file has not the right format

### ISSUE THREAD

**Issue by wmbio** [SilvioWeging/kASA#5]
Hi~
When I use 'kASA_linux build' build an Index based on a content.txt file obtained through 'kASA_linux generateCF .... -u subspecies', I got an error: ERROR: content file has not the right format. Taxids in the second row are required to be integers! But, some bacteria subspecies taxids are not integers. e.g x1379. Is this a bug? Would you help to fix it. Thanks!

**Comment by ghost** [comment]
Hey there,
you're lucky to have found a not yet finished feature currently in development: adding non-numeric taxids :D
Currently only creating a content file works correctly but not the rest since my first solution was to directly save the taxid and not the line index in the content file (updating and deleting entries would mess with it for example). Therefore it's not really a bug as NCBI taxids (read: numbers) are required for the program to work. For now you could hack this with a table which maps your taxids to numbers and replace them in the content file. Sorry for this inconvenience, I'll try to get it working in about to weeks from now.

**Comment by ghost** [comment]
Feature added with commit 2ec6b28e8cf61988ccd2c27ef6c2d93e4822a15f
(Use `--taxidasstr` during build or generateCF to create a new content file now containing numeric IDs in the fifth column. Afterwards, the new content file format is recognised automatically.)
