### ISSUE TITLE
running time for building database

### ISSUE THREAD

**Issue by tothuhien** [SilvioWeging/kASA#9]
Hi, I'm try to build a database for kASA that includes 40 genomes (in total about 11G) using 10 cores and 30G. The job has been running for almost 3 days and hasn't been finished yet. I'm wondering if it's normal or is there any issue?
Thanks in advance.
Best regards,
Hien

**Comment by ghost** [comment]
Greetings Hien,

I'll need some info first:
- list of used parameters
- SSD or HDD?
- version of kASA (usually printed at program start)
- are the files gzipped or not? Or rather: is a progress percentage being printed to the terminal/file?
- operating system & platform (cluster, PC, laptop)

Thanks

**Comment by tothuhien** [comment]
Hi, thanks for your quick response. 

The genome files are zipped with gzip. There's not any progress percentage printed. This is the whole log file now:

> OUT: kASA version 1.4.7 ran on Linux at Wed Mar 13 17:56:20 2023
OUT: kASA build -c database/kASA/db/content.tsv -d database/kASA/db/index_40 -i database/kASA/db/assemblies/ -m 30g -n 10 -t kASA/tmp 
OUT: STXXL-MSG STXXL v1.4.99 (prerelease/Release)
OUT: STXXL-MSG Disk 'kASA/tmpstxxl_temp_0.tmp' is allocated, space: 1 MiB, I/O implementation: syscall delete_on_exit direct=on queue=0 devid=0 unlink_on_open

I'm running it on a slurm cluster

Best regards,

**Comment by ghost** [comment]
Thanks for the info!
There are some issues with your call. It should be:
`kASA build -c database/kASA/db/content.tsv -d database/kASA/db/index_40 -i database/kASA/db/assemblies/ -m 30 -n 10 -t kASA/tmp/`
Because 1. the memory flag must have no letter next to the number. It's always in Gigabytes. 2. the temporary folder needs to end with a /. 
Maybe try that first. If it does not print more than you've already seen, try adding --debug to your call and send me the output please.

Just in general: If your cluster is using HDDs then kASA will take a while because it wasn't designed for them.

**Comment by tothuhien** [comment]
Thank you. I've edited the script as you told and re -launched the job. I will update the progress.

Best,

**Comment by tothuhien** [comment]
sorry I forgot to update that the job had finished successfully after running for about 1 day.
Thanks for your help.
